[package]
name = "servo-script-webcrypto"
build = "build.rs"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "script_webcrypto"
path = "lib.rs"

[lints]
workspace = true

[dependencies]
aes = { workspace = true }
aes-gcm = { workspace = true }
aes-kw = { workspace = true }
argon2 = { workspace = true }
aws-lc-rs = { workspace = true }
base64ct = { workspace = true }
cbc = { workspace = true }
chacha20poly1305 = { workspace = true }
crypto-bigint = { workspace = true }
cshake = { workspace = true }
ctr = { workspace = true }
ctutils = { workspace = true }
deny_public_fields = { workspace = true }
dom_struct = { workspace = true }
ecdsa = { workspace = true }
ed25519-dalek = { workspace = true }
ed448-goldilocks = { workspace = true }
elliptic-curve = { workspace = true }
hkdf = { workspace = true }
itertools = { workspace = true }
js = { workspace = true }
jstraceable_derive = { workspace = true }
k12 = { workspace = true }
keccak = { workspace = true }
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }
ml-dsa = { workspace = true }
ml-kem = { workspace = true }
ocb3 = { workspace = true }
p256 = { workspace = true }
p384 = { workspace = true }
p521 = { workspace = true }
pkcs8 = { workspace = true }
rand = { workspace = true }
rsa = { workspace = true }
rustc-hash = { workspace = true }
script_bindings = { workspace = true, features = ["webcrypto"] }
serde_core = { workspace = true }
servo-base = { workspace = true }
servo-constellation-traits = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
sponge-cursor = { workspace = true }
strum = { workspace = true }
trait-set = { workspace = true }
x-wing = { workspace = true }
x25519-dalek = { workspace = true }
x448 = { workspace = true }
zeroize = { workspace = true }
